### ISSUE TITLE
README missing `@hey-api/openapi-ts` installation instruction

### ISSUE THREAD

**Issue by omeralpi** [aknslc/heyapi-client-generator#3]
> [!WARNING]
> When running `pnpm run generate-client`, I encountered the error:
> `Cannot find module @hey-api/openapi-ts`

It seems that the `@hey-api/openapi-ts` package is required but not mentioned in the `heyapi-client-generator` README.
Please update the README to include this missing dependency in the installation instructions.

> [!NOTE]
> May be; to resolve the issue, run this command: `pnpm add -D heyapi-client-generator @hey-api/openapi-ts`

**Comment by aknslc** [comment]
Related bug fixed. Thanks for your support.

**Comment by aknslc** [comment]
Related bug fixed. Thanks for your support.
