### ISSUE TITLE
Unable to see `ServiceConfig` types or get type validation in `heyapi-client-generator`

### ISSUE THREAD

**Issue by omeralpi** [aknslc/heyapi-client-generator#4]
I am working with `heyapi-client-generator` and trying to define a `ServiceConfig` in my code as shown below. However, I cannot see the `ServiceConfig` types, and even if I write `ServiceConfig` incorrectly (for example, typing serviceeeeconfig), it does not throw any errors.

**Comment by aknslc** [comment]
Related bug fixed. Thanks for your support.
