### ISSUE TITLE
README missing `@hey-api/client-axios` installation instruction

### ISSUE THREAD

**Issue by omeralpi** [aknslc/heyapi-client-generator#5]
The file generated by `@hey-api/openapi-ts` includes an import for `@hey-api/client-axios`, but the README is missing installation instructions for this dependency. To avoid any missing dependency errors, the README needs to be updated to include the installation command for `@hey-api/client-axios`.

![Screenshot 2024-11-19 at 13 31 17](https://github.com/user-attachments/assets/cfa55f5a-604d-4349-baca-b7ab5cbba712)

**Comment by aknslc** [comment]
Related bug fixed. Thanks for your support.
